services:
  image-builder:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: rpi-image-builder
    restart: unless-stopped
    volumes:
      - ./config:/home/imagegen/rpi-image-gen/packet-run
      - ./deploy:/home/imagegen/rpi-image-gen/deploy
    working_dir: /home/imagegen/rpi-image-gen
    command: sh -c './build.sh -D ./packet-run -c generic64-apt-pi4 -o ./packet-run/my.options; mv /home/imagegen/rpi-image-gen/work/deb12-arm64-min/artefacts/deb12-arm64-min.* ./deploy/'
    privileged: true
