---
name: packet-run-base
mmdebstrap:
  setup-hooks:
  - mkdir -p $1/etc/apt/trusted.gpg.d/
  # Nodejs repo key
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | apt-key --keyring $1/etc/apt/trusted.gpg.d/nodesource.gpg add -
  # Tailscale repo key
  - curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | apt-key --keyring $1/etc/apt/trusted.gpg.d/tailscale.gpg add -

  mirrors:
  # Nodejs repo
  - deb [arch=arm64 trusted=yes] https://deb.nodesource.com/node_20.x nodistro main
  # Tailscale repo
  - deb [trusted=yes] https://pkgs.tailscale.com/stable/debian bookworm main

  customize-hooks:
  # Create packet_run_config.txt from template
  - |
    cat ./packet-run/packet_run_config.txt.tpl | sed \
      -e "s|<PACKET_RUN_TERMINAL_ID>|${IGconf_packet_run_terminal_id}|g" \
      -e "s|<PACKET_RUN_SERVER_IP>|${IGconf_packet_run_server_ip}|g" \
      -e "s|<TAILSCALE_AUTH_KEY>|${IGconf_tailscale_auth_key}|g" \
      -e "s|<TAILSCALE_LOGIN_SERVER>|${IGconf_tailscale_login_server:-https://login.tailscale.com}|g" \
      > $1/boot/firmware/packet_run_config.txt

  # Create tailscale service from template
  - |
    cat ./packet-run/tailscale.service.tpl | sed \
      -e "s|<SERVICE_USER>|${IGconf_device_user1}|g" \
      > $1/etc/systemd/system/tailscale.service

  # Copy common rootfs-overlay
  - cp -R ./packet-run/image/device/rootfs-overlay/* $1/

  # Enable services
  - $BDEBSTRAP_HOOKS/enable-units "$1" overlayfs-check tailscale

  packages:
  - nodejs
  - tailscale
  - cage
  - vim
  - git
  - raspi-config