---
name: packet-run-client
mmdebstrap:
  customize-hooks:
  - |
    # Load application code
    cp -R /opt/packet-run/client $1/opt/packet-run/client/

    # Install hall-sensor-server dependencies
    cd $1/opt/packet-run/client/hall-sensor-server
    npm install

    # Make boot script executable
    chmod +x $1/opt/packet-run/client/boot_packet_run.sh

    # Create packet_run_config.txt from template
    cat ./packet_run_config.txt.tpl | sed \
      -e "s|<PACKET_RUN_TERMINAL_ID>|${IGconf_packet_run_terminal_id}|g" \
      -e "s|<PACKET_RUN_SERVER_IP>|${IGconf_packet_run_server_ip}|g" \
      -e "s|<TAILSCALE_AUTH_KEY>|${IGconf_tailscale_auth_key}|g" \
      -e "s|<TAILSCALE_LOGIN_SERVER>|${IGconf_tailscale_login_server:-https://login.tailscale.com}|g" \
      > $1/boot/packet_run_config.txt

    # Create hall-sensor-server service from template
    cat ./packet-run/hall-sensor-server.service.tpl | sed \
      -e "s|<SERVICE_USER>|${IGconf_device_user1}|g" \
      > $1/etc/systemd/system/hall-sensor-server.service

    # Create kiosk service from template
    cat ./packet-run/kiosk.service.tpl | sed \
      -e "s|<SERVICE_USER>|${IGconf_device_user1}|g" \
      > $1/etc/systemd/system/kiosk.service

    # Enable services
    $BDEBSTRAP_HOOKS/enable-units "$1" hall-sensor-server kiosk

  packages:
  - chromium